# Generated by Django 5.2.3 on 2025-09-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_historialclinico_recetamedica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='alergias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='antecedentes',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='enfermedades_cronicas',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
